// larecomp - ReXGlue Recompiled Project
// Generated by: rexglue init

#include "generated/larecomp_config.h"
#include "generated/larecomp_init.h"

#include <rex/cvar.h>
#include <rex/filesystem.h>
#include <rex/runtime.h>
#include <rex/logging.h>
#include <rex/kernel/xthread.h>
#include <rex/kernel/kernel_state.h>
#include <rex/graphics/graphics_system.h>
#include <rex/ui/window.h>
#include <rex/ui/window_listener.h>
#include <rex/ui/windowed_app.h>
#include <rex/ui/graphics_provider.h>
#include <rex/ui/immediate_drawer.h>
#include <rex/ui/imgui_drawer.h>
#include <rex/ui/imgui_dialog.h>

#include <imgui.h>

#include <atomic>
#include <filesystem>
#include <thread>

// Macros para definir as funções exportadas, simulando o comportamento da DLL
#define EXPORT extern "C" __declspec(dllexport)

// --- XAM Stubs ---
EXPORT DWORD _XamShowFriendsUI(DWORD dwUserIndex) {
    printf("[Stub] _XamShowFriendsUI called\n");
    return 0; // Ou um código de erro HRESULT apropriado
}

EXPORT DWORD _XamShowGamerCardUIForXUID(DWORD dwUserIndex, uint64_t xuid) {
    printf("[Stub] _XamShowGamerCardUIForXUID called\n");
    return 0;
}

EXPORT DWORD _XamShowAchievementsUI(DWORD dwUserIndex) {
    printf("[Stub] _XamShowAchievementsUI called\n");
    return 0;
}

EXPORT DWORD _XamShowPlayerReviewUI(DWORD dwUserIndex, uint64_t xuid) {
    printf("[Stub] _XamShowPlayerReviewUI called\n");
    return 0;
}

EXPORT DWORD _XamShowMarketplaceUI(DWORD dwUserIndex, DWORD dwEntryPoint, ULONGLONG dwOfferId, DWORD dwContentCategories) {
    printf("[Stub] _XamShowMarketplaceUI called\n");
    return 0;
}

EXPORT DWORD _XamUserCreateStatsEnumerator(DWORD dwUserIndex, DWORD dwNumRows, DWORD dwNumCols, DWORD pdwSpecs, DWORD pdwBuffer, DWORD pcbBuffer, DWORD phEnum) {
    printf("[Stub] _XamUserCreateStatsEnumerator called\n");
    return 0;
}


// --- NetDll Stubs ---
EXPORT int _NetDll_getsockname(int s, struct sockaddr *name, int *namelen) {
    printf("[Stub] _NetDll_getsockname called\n");
    return -1; // Socket error
}

EXPORT int _NetDll_XNetRegisterKey(DWORD pKeyId, DWORD pKey) {
    printf("[Stub] _NetDll_XNetRegisterKey called\n");
    return 0; 
}

EXPORT int _NetDll_XNetUnregisterKey(DWORD pKeyId) {
    printf("[Stub] _NetDll_XNetUnregisterKey called\n");
    return 0;
}

EXPORT int _NetDll_XNetServerToInAddr(DWORD ina, DWORD pKeyId, DWORD pina) {
    printf("[Stub] _NetDll_XNetServerToInAddr called\n");
    return 0;
}

EXPORT int _NetDll_XNetUnregisterInAddr(DWORD ina) {
    printf("[Stub] _NetDll_XNetUnregisterInAddr called\n");
    return 0;
}

EXPORT int _NetDll_XNetConnect(DWORD ina) {
    printf("[Stub] _NetDll_XNetConnect called\n");
    return 0;
}

EXPORT int _NetDll_XNetGetConnectStatus(DWORD ina) {
    printf("[Stub] _NetDll_XNetGetConnectStatus called\n");
    return 0; // Not connected
}

EXPORT int _NetDll_XNetQosLookup(DWORD pQosInfo, DWORD pqnInfo, DWORD pqnAddr, DWORD dwFlags, DWORD dwBitsPerSec, DWORD dwServiceId, DWORD dwNumQosProbes, DWORD dwBitsPerSecRcv, DWORD hEvent, DWORD pXnQnRet) {
    printf("[Stub] _NetDll_XNetQosLookup called\n");
    return 0;
}

EXPORT DWORD _XNetLogonGetTitleID() {
    printf("[Stub] _XNetLogonGetTitleID called\n");
    return 0;
}

// --- Kernel/IO Stubs ---
EXPORT DWORD _IoDismountVolume(DWORD DeviceObject) {
    printf("[Stub] _IoDismountVolume called\n");
    return 0;
}

EXPORT DWORD _IoInvalidDeviceRequest(DWORD DeviceObject, DWORD Irp) {
    printf("[Stub] _IoInvalidDeviceRequest called\n");
    return 0;
}

EXPORT void _ObReferenceObject(void* Object) {
    printf("[Stub] _ObReferenceObject called\n");
}

EXPORT void _IoDeleteDevice(DWORD DeviceObject) {
    printf("[Stub] _IoDeleteDevice called\n");
}

EXPORT void _IoCompleteRequest(DWORD Irp, char PriorityBoost) {
    printf("[Stub] _IoCompleteRequest called\n");
}

EXPORT WCHAR _RtlUpcaseUnicodeChar(WCHAR SourceCharacter) {
    // Basic stub, just returns the character
    // A real implementation would convert lowercase to uppercase
    return SourceCharacter;
}

EXPORT BOOLEAN _ObIsTitleObject(void* Object) {
    printf("[Stub] _ObIsTitleObject called\n");
    return 1; // Assuming true for title objects
}

EXPORT DWORD _IoCheckShareAccess(DWORD DesiredAccess, DWORD DesiredShareAccess, void* FileObject, void* ShareAccess, BOOLEAN Update) {
    printf("[Stub] _IoCheckShareAccess called\n");
    return 0; // STATUS_SUCCESS equivalent
}

EXPORT void _IoSetShareAccess(DWORD DesiredAccess, DWORD DesiredShareAccess, void* FileObject, void* ShareAccess) {
    printf("[Stub] _IoSetShareAccess called\n");
}

EXPORT void _IoRemoveShareAccess(void* FileObject, void* ShareAccess) {
    printf("[Stub] _IoRemoveShareAccess called\n");
}

// --- Voice/Audio Stubs ---
EXPORT DWORD _XamVoiceSubmitPacket(DWORD hVoiceDecodeHandle, void* pBuffer, DWORD dwBufferSize, void* pContext) {
    printf("[Stub] _XamVoiceSubmitPacket called\n");
    return 0; // HRESULT success equivalent
}

class DebugOverlayDialog : public rex::ui::ImGuiDialog {
public:
    DebugOverlayDialog(rex::ui::ImGuiDrawer* imgui_drawer)
        : ImGuiDialog(imgui_drawer) {}
protected:
    void OnDraw(ImGuiIO& io) override {
        ImGui::SetNextWindowPos(ImVec2(10, 10), ImGuiCond_FirstUseEver);
        ImGui::SetNextWindowSize(ImVec2(220, 60), ImGuiCond_FirstUseEver);
        ImGui::SetNextWindowBgAlpha(0.5f);
        if (ImGui::Begin("Debug##overlay", nullptr, ImGuiWindowFlags_NoCollapse)) {
            ImGui::Text("%.1f FPS (%.2f ms)", io.Framerate, 1000.0f / io.Framerate);
        }
        ImGui::End();
    }
};

class LarecompApp : public rex::ui::WindowedApp, public rex::ui::WindowListener {
public:
    static std::unique_ptr<rex::ui::WindowedApp> Create(rex::ui::WindowedAppContext& ctx) {
        return std::make_unique<LarecompApp>(ctx);
    }

    LarecompApp(rex::ui::WindowedAppContext& ctx)
        : WindowedApp(ctx, "larecomp", "[game_directory]") {
        AddPositionalOption("game_directory");
    }

    bool OnInitialize() override {
        auto exe_dir = rex::filesystem::GetExecutableFolder();

        // Game directory: arg or default to exe_dir/assets
        std::filesystem::path game_dir;
        if (auto arg = GetArgument("game_directory")) {
            game_dir = *arg;
        } else {
            game_dir = exe_dir / "assets";
        }

        // Forcing logs so you don't have to type in the terminal every time 
        std::string log_file_cvar = "debug_mcla.txt"; 
        std::string log_level_str = "trace";

        if (REXCVAR_GET(log_verbose) && log_level_str == "info") {
            log_level_str = "trace";
        }

        auto log_config = rex::BuildLogConfig(
            log_file_cvar.empty() ? nullptr : log_file_cvar.c_str(),
            log_level_str, {});
        rex::InitLogging(log_config);
        rex::RegisterLogLevelCallback();
        REXLOG_INFO("larecomp starting");
        REXLOG_INFO("  Game directory: {}", game_dir.string());

        // Create and initialize runtime
        runtime_ = std::make_unique<rex::Runtime>(game_dir);
        runtime_->set_app_context(&app_context());

        auto status = runtime_->Setup(
            static_cast<uint32_t>(PPC_CODE_BASE),
            static_cast<uint32_t>(PPC_CODE_SIZE),
            static_cast<uint32_t>(PPC_IMAGE_BASE),
            static_cast<uint32_t>(PPC_IMAGE_SIZE),
            PPCFuncMappings);
        if (XFAILED(status)) {
            REXLOG_ERROR("Runtime setup failed: {:08X}", status);
            return false;
        }

        // Load XEX image
        status = runtime_->LoadXexImage("game:\\default.xex");
        if (XFAILED(status)) {
            REXLOG_ERROR("Failed to load XEX: {:08X}", status);
            return false;
        }

        // Create window
        window_ = rex::ui::Window::Create(app_context(), "larecomp", 1280, 720);
        if (!window_) {
            REXLOG_ERROR("Failed to create window");
            return false;
        }

        window_->AddListener(this);
        window_->Open();

        // Setup graphics presenter and ImGui
        auto* graphics_system = runtime_->graphics_system();
        if (graphics_system && graphics_system->presenter()) {
            auto* presenter = graphics_system->presenter();
            auto* provider = graphics_system->provider();
            if (provider) {
                immediate_drawer_ = provider->CreateImmediateDrawer();
                if (immediate_drawer_) {
                    immediate_drawer_->SetPresenter(presenter);
                    imgui_drawer_ = std::make_unique<rex::ui::ImGuiDrawer>(window_.get(), 64);
                    imgui_drawer_->SetPresenterAndImmediateDrawer(presenter, immediate_drawer_.get());
                    debug_overlay_ = std::unique_ptr<DebugOverlayDialog>(
                        new DebugOverlayDialog(imgui_drawer_.get()));
                    runtime_->set_display_window(window_.get());
                    runtime_->set_imgui_drawer(imgui_drawer_.get());
                }
            }
            window_->SetPresenter(presenter);
        }

        // Launch module in background
        app_context().CallInUIThreadDeferred([this]() {
            auto main_thread = runtime_->LaunchModule();
            if (!main_thread) {
                REXLOG_ERROR("Failed to launch module");
                app_context().QuitFromUIThread();
                return;
            }

            module_thread_ = std::thread([this, main_thread = std::move(main_thread)]() mutable {
                main_thread->Wait(0, 0, 0, nullptr);
                REXLOG_INFO("Execution complete");
                if (!shutting_down_.load(std::memory_order_acquire)) {
                    app_context().CallInUIThread([this]() {
                        app_context().QuitFromUIThread();
                    });
                }
            });
        });

        return true;
    }

    void OnClosing(rex::ui::UIEvent& e) override {
        (void)e;
        REXLOG_INFO("Window closing, shutting down...");
        shutting_down_.store(true, std::memory_order_release);
        if (runtime_ && runtime_->kernel_state()) {
            runtime_->kernel_state()->TerminateTitle();
        }
        app_context().QuitFromUIThread();
    }

    void OnDestroy() override {
        // ImGui cleanup (reverse of setup)
        debug_overlay_.reset();
        if (imgui_drawer_) {
            imgui_drawer_->SetPresenterAndImmediateDrawer(nullptr, nullptr);
            imgui_drawer_.reset();
        }
        if (immediate_drawer_) {
            immediate_drawer_->SetPresenter(nullptr);
            immediate_drawer_.reset();
        }
        if (runtime_) {
            runtime_->set_display_window(nullptr);
            runtime_->set_imgui_drawer(nullptr);
        }
        // Window/runtime cleanup
        if (window_) {
            window_->SetPresenter(nullptr);
        }
        if (module_thread_.joinable()) {
            module_thread_.join();
        }
        if (window_) {
            window_->RemoveListener(this);
        }
        window_.reset();
        runtime_.reset();
    }

private:
    std::unique_ptr<rex::Runtime> runtime_;
    std::unique_ptr<rex::ui::Window> window_;
    std::thread module_thread_;
    std::atomic<bool> shutting_down_{false};
    std::unique_ptr<rex::ui::ImmediateDrawer> immediate_drawer_;
    std::unique_ptr<rex::ui::ImGuiDrawer> imgui_drawer_;
    std::unique_ptr<DebugOverlayDialog> debug_overlay_;
};

XE_DEFINE_WINDOWED_APP(larecomp, LarecompApp::Create)