// larecomp - ReXGlue Recompiled Project
// Generated by: rexglue init
//
// This file is SDK-managed. Customizations go in virtual hook overrides.
// Running 'rexglue migrate' will overwrite this file.

#include "generated/larecomp_config.h"
#include "generated/larecomp_init.h"

#include <rex/rex_app.h>

extern "C" {
    // XAM Stubs
    uint32_t _XamShowFriendsUI(uint32_t dwUserIndex) { return 0; }
    uint32_t _XamShowGamerCardUIForXUID(uint32_t dwUserIndex, uint64_t xuid) { return 0; }
    uint32_t _XamShowAchievementsUI(uint32_t dwUserIndex) { return 0; }
    uint32_t _XamShowPlayerReviewUI(uint32_t dwUserIndex, uint64_t xuid) { return 0; }
    uint32_t _XamShowMarketplaceUI(uint32_t dwUserIndex, uint32_t dwEntryPoint, uint64_t dwOfferId, uint32_t dwContentCategories) { return 0; }
    uint32_t _XamUserCreateStatsEnumerator(uint32_t dwUserIndex, uint32_t dwNumRows, uint32_t dwNumCols, uint32_t pdwSpecs, uint32_t pdwBuffer, uint32_t pcbBuffer, uint32_t phEnum) { return 0; }
    uint32_t _XamVoiceSubmitPacket(uint32_t hVoiceDecodeHandle, void* pBuffer, uint32_t dwBufferSize, void* pContext) { return 0; }

    // NetDll Stubs
    int _NetDll_getsockname(int s, struct sockaddr *name, int *namelen) { return -1; }
    int _NetDll_XNetRegisterKey(uint32_t pKeyId, uint32_t pKey) { return 0; }
    int _NetDll_XNetUnregisterKey(uint32_t pKeyId) { return 0; }
    int _NetDll_XNetServerToInAddr(uint32_t ina, uint32_t pKeyId, uint32_t pina) { return 0; }
    int _NetDll_XNetUnregisterInAddr(uint32_t ina) { return 0; }
    int _NetDll_XNetConnect(uint32_t ina) { return 0; }
    int _NetDll_XNetGetConnectStatus(uint32_t ina) { return 0; }
    int _NetDll_XNetQosLookup(uint32_t pQosInfo, uint32_t pqnInfo, uint32_t pqnAddr, uint32_t dwFlags, uint32_t dwBitsPerSec, uint32_t dwServiceId, uint32_t dwNumQosProbes, uint32_t dwBitsPerSecRcv, uint32_t hEvent, uint32_t pXnQnRet) { return 0; }
    uint32_t _XNetLogonGetTitleID() { return 0; }

    // Kernel/IO Stubs
    uint32_t _IoDismountVolume(uint32_t DeviceObject) { return 0; }
    uint32_t _IoInvalidDeviceRequest(uint32_t DeviceObject, uint32_t Irp) { return 0; }
    void _ObReferenceObject(void* Object) {}
    void _IoDeleteDevice(uint32_t DeviceObject) {}
    void _IoCompleteRequest(uint32_t Irp, char PriorityBoost) {}
    wchar_t _RtlUpcaseUnicodeChar(wchar_t SourceCharacter) { return SourceCharacter; }
    bool _ObIsTitleObject(void* Object) { return true; }
    uint32_t _IoCheckShareAccess(uint32_t DesiredAccess, uint32_t DesiredShareAccess, void* FileObject, void* ShareAccess, bool Update) { return 0; }
    void _IoSetShareAccess(uint32_t DesiredAccess, uint32_t DesiredShareAccess, void* FileObject, void* ShareAccess) {}
    void _IoRemoveShareAccess(void* FileObject, void* ShareAccess) {}
}

class LARecompApp : public rex::ReXApp {
 public:
  using rex::ReXApp::ReXApp;

  static std::unique_ptr<rex::ui::WindowedApp> Create(
      rex::ui::WindowedAppContext& ctx) {
    return std::unique_ptr<ProjectLaApp>(new ProjectLaApp(ctx, "larecomp",
        {PPC_CODE_BASE, PPC_CODE_SIZE, PPC_IMAGE_BASE,
         PPC_IMAGE_SIZE, PPCFuncMappings}));
  }

};

REX_DEFINE_APP(larecomp, LARecompApp::Create)
